// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0J4H--iwM1LYDrkkd0CL0Hvi4jyg1I_s',
    appId: '1:369146945377:web:544e383db46ad37dc6af20',
    messagingSenderId: '369146945377',
    projectId: 'nature-noise-6d9b5',
    authDomain: 'nature-noise-6d9b5.firebaseapp.com',
    storageBucket: 'nature-noise-6d9b5.firebasestorage.app',
    measurementId: 'G-LL2JG6D5SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYfYlasC6tb-tEiO-zCCLTWPSdwyiLBw0',
    appId: '1:369146945377:android:5590ff743f3ae090c6af20',
    messagingSenderId: '369146945377',
    projectId: 'nature-noise-6d9b5',
    storageBucket: 'nature-noise-6d9b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_r8_8LV3ddG3wR9IJlj4pXEozS5FrOgA',
    appId: '1:369146945377:ios:190a0dca1167283cc6af20',
    messagingSenderId: '369146945377',
    projectId: 'nature-noise-6d9b5',
    storageBucket: 'nature-noise-6d9b5.firebasestorage.app',
    iosBundleId: 'com.example.natureNoise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_r8_8LV3ddG3wR9IJlj4pXEozS5FrOgA',
    appId: '1:369146945377:ios:190a0dca1167283cc6af20',
    messagingSenderId: '369146945377',
    projectId: 'nature-noise-6d9b5',
    storageBucket: 'nature-noise-6d9b5.firebasestorage.app',
    iosBundleId: 'com.example.natureNoise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0J4H--iwM1LYDrkkd0CL0Hvi4jyg1I_s',
    appId: '1:369146945377:web:c91250bb93fa6ed0c6af20',
    messagingSenderId: '369146945377',
    projectId: 'nature-noise-6d9b5',
    authDomain: 'nature-noise-6d9b5.firebaseapp.com',
    storageBucket: 'nature-noise-6d9b5.firebasestorage.app',
    measurementId: 'G-BT3W0GZT5M',
  );

}